// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK5SpkadeRi8xEKy7g1tnaq6heH9iz3-Y',
    appId: '1:903922673374:web:bc664677681ff785c0044f',
    messagingSenderId: '903922673374',
    projectId: 'cybert-agro',
    authDomain: 'cybert-agro.firebaseapp.com',
    storageBucket: 'cybert-agro.appspot.com',
    measurementId: 'G-JKWCP7GLCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7GwNgnW10wQtqv7EEJSCJv8oUPP7B4xY',
    appId: '1:903922673374:android:e55f6d783faea019c0044f',
    messagingSenderId: '903922673374',
    projectId: 'cybert-agro',
    storageBucket: 'cybert-agro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1BLXuHqJoJEKjpFxVEJYwRSjP43CZgFs',
    appId: '1:903922673374:ios:0b6d2b72ad263959c0044f',
    messagingSenderId: '903922673374',
    projectId: 'cybert-agro',
    storageBucket: 'cybert-agro.appspot.com',
    androidClientId: '903922673374-s4s52f3ce3o4bqfiv0fel4coc4t5in72.apps.googleusercontent.com',
    iosClientId: '903922673374-mhl5gtto2gsshrct7m80a446cbn48kg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.cyberagroapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1BLXuHqJoJEKjpFxVEJYwRSjP43CZgFs',
    appId: '1:903922673374:ios:0b6d2b72ad263959c0044f',
    messagingSenderId: '903922673374',
    projectId: 'cybert-agro',
    storageBucket: 'cybert-agro.appspot.com',
    androidClientId: '903922673374-s4s52f3ce3o4bqfiv0fel4coc4t5in72.apps.googleusercontent.com',
    iosClientId: '903922673374-mhl5gtto2gsshrct7m80a446cbn48kg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.cyberagroapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK5SpkadeRi8xEKy7g1tnaq6heH9iz3-Y',
    appId: '1:903922673374:web:80f39a263b11ca36c0044f',
    messagingSenderId: '903922673374',
    projectId: 'cybert-agro',
    authDomain: 'cybert-agro.firebaseapp.com',
    storageBucket: 'cybert-agro.appspot.com',
    measurementId: 'G-XPSQZ2VM9Y',
  );
}
